version: '3.8'
services:

  userop_srv:
    build:
      context: .
      dockerfile: userop_srv/Dockerfile
    image: zhengpanone/mxshop_srvs/userop_srv
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
