basePath: /v1/oss
definitions:
  utils.ErrorItem:
    properties:
      error:
        type: string
      key:
        type: string
    type: object
  utils.Meta:
    properties:
      request_id:
        type: string
    type: object
  utils.Response:
    properties:
      code:
        description: 业务状态码
        type: integer
      data:
        description: 响应数据
      errors:
        description: Errors 错误提示，如 xx字段不能为空等
        items:
          $ref: '#/definitions/utils.ErrorItem'
        type: array
      meta:
        allOf:
        - $ref: '#/definitions/utils.Meta'
        description: Meta 源数据,存储如请求ID,分页等信息
      msg:
        description: 提示信息
        type: string
    type: object
host: 127.0.0.1:18022
info:
  contact:
    name: zhengpanone
    url: http://127.0.0.1:18022/swagger/index.html
  description: 慕学商城项目，提供订单的查询、创建、更新等功能。
  title: oss服务
  version: "1.0"
paths:
  /v1/oss/callback:
    post:
      consumes:
      - application/json
      description: 处理上传回调请求
      parameters:
      - description: 认证令牌
        in: header
        name: x-token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: 品牌创建成功
          schema:
            $ref: '#/definitions/utils.Response'
        "400":
          description: 无效的请求参数
          schema:
            $ref: '#/definitions/utils.Response'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 处理上传回调请求
      tags:
      - OSS
  /v1/oss/token:
    get:
      consumes:
      - application/json
      description: 生成上传凭证
      parameters:
      - description: 认证令牌
        in: header
        name: x-token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: 品牌创建成功
          schema:
            $ref: '#/definitions/utils.Response'
        "400":
          description: 无效的请求参数
          schema:
            $ref: '#/definitions/utils.Response'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 生成上传凭证
      tags:
      - OSS
  /v1/oss/upload:
    post:
      consumes:
      - application/json
      description: 文件上传接口
      parameters:
      - description: 认证令牌
        in: header
        name: x-token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: 品牌创建成功
          schema:
            $ref: '#/definitions/utils.Response'
        "400":
          description: 无效的请求参数
          schema:
            $ref: '#/definitions/utils.Response'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 文件上传接口
      tags:
      - OSS
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
tags:
- description: 提供oss的增删改查功能
  name: oss管理
