nacos:
  host: 127.0.0.1
  port: 30848
  context-path: /nacos
  namespace: ac2997b0-1569-47d9-a792-efc10375341b
  dataId: user-web.yaml
  group: dev
  user: nacos
  password: nacos

log:
  filename: 'user-web.log'